### ISSUE TITLE
Advanced example config files

### ISSUE THREAD

**Issue by revuwa** [vars1ty/HybridBar#19]
Let's say, I'm more nosy than lazy, (and my grandma has no time, btw).
But I can't imaging what functionality the first three widgets (after the username), at the top bar of your [screenshot](https://user-images.githubusercontent.com/54314240/197680577-2bc0cff4-2438-4c8d-8428-11499d0519c6.png) could have, so I just kindly wanted to ask, if you're possibly willing to share that configs as a bit more extended examples?

As some kind of 'proof' that I not just want to use your configs, I made a screenshot of my current bar config:
![HybridBar](https://user-images.githubusercontent.com/7300276/201488356-7d72ecd7-5d3e-488f-bd13-261c7ef0cdfd.png)
If you insist, I could upload my configs here, and we could do some kind of swap, if you like 😉

PS: Completely off topic, but I just wanted to let you know, that there seems to be a (Wayland targeted and GTK using) [Hybridbar](https://github.com/hcsubser/hybridbar), already - if you shouldn't be be aware of it, already; and even if I know that: 
HybridBar =! Hybridbar ✌️

**Comment by vars1ty** [comment]
Yeah sure, I'll attach it below.
Here's how it's structured:
1. Username
2. Hyprland: Current Workspace / Max Workspaces
3. Hyprland: Currently focused window
4. Cava
5. Speaker Volume
6. Current Time
7. Custom hot-reload

**Comment by vars1ty** [comment]
config.json
```json
{
    "hybrid": {
        "cava_sed": "s/;//g;s/0/▁ /g;s/1/▂ /g;s/2/▃ /g;s/3/▄ /g;s/4/▅ /g;s/5/▆ /g;s/6/▇ /g;s/7/█/g;",
        "stylesheet": "style.css",
        "cava_framerate": 360,
        "expand_right": false,
        "expand_left": false,
        "update_rate": 69,
        "cava_bars": 7,
        "r": 10,
        "g": 10,
        "b": 10,
        "a": 0.5
    },
    "variables": {
        "@reload": "killall -I hybrid-bar -9 ; hyprctl dispatch exec hybrid-bar ; hyprctl dispatch exec \"HYBRID_CONFIG=config_bottom.json hybrid-bar\"",
        "@get": "jq -r",
        "$+s": "<small>",
        "$-s": "</small>"
    },
    "left-label_username": {
        "text": "  visions",
        "tooltip": "$+sCurrent Username$-s"
    },
    "left-spacing_separator": {
        "spacing_start": 5,
        "spacing_end": 7
    },
    "left-label_current_workspace": {
        "text": " 𧻓 ",
        "command": "hyprctl monitors -j | @get '.[].activeWorkspace.id'",
        "tooltip": "$+sCurrent Hyprland Workspace (0-10)$-s"
    },
    "left-label_max_workspaces": {
        "text": "/10"
    },
    "left-spacing_1": {
        "spacing_start": 5
    },
    "centered-label_active_window": {
        "text": "  ",
        "command": "hyprctl activewindow -j | @get '.title'",
        "tooltip": "$+sCurrently focused window$-s"
    },
    "centered-spacing_2": {
        "spacing_start": 5
    },
    "right-spacing_3": {
        "spacing_start": 5
    },
    "right-box_4": {
        "?": "This exists because spacings didn't work for this use-case.",
        "width": 5
    },
    "right-cava_5": {},
    "right-spacing_separator_vol": {
        "spacing_start": 5,
        "spacing_end": 7
    },
    "right-label_volume": {
        "text": "  ",
        "command": "echo $(pactl get-sink-volume @DEFAULT_SINK@ | rg -o '[0-9]{1,3}%' | head -n 1 | cut -d '%' -f 1)%",
        "tooltip": "$+sVolume percentage (%)$-s"
    },
    "right-spacing_separator": {
        "spacing_start": 5,
        "spacing_end": 7
    },
    "right-label_time": {
        "text": "  ",
        "command": "date +%H:%M",
        "tooltip": "$+sCurrent hour:minute$-s"
    },
    "right-spacing_separator_ending": {
        "spacing_start": 5,
        "spacing_end": 7
    },
    "right-button_reload": {
        "text": "",
        "command": "@reload",
        "tooltip": "$+sReload$-s"
    }
}
```

style.css
```css
/* Label Color. Config default is white. */
label {
    color:         white;
}

#root {
    border-bottom: 1px solid; 
}

#left {
    border-right: 1px solid;
    border-left: 1px solid;
}

#right {
    border-left: 1px solid;
    border-right: 1px solid;
}

#separator, #separator_ending, #separator_vol {
    background-color: white;
}

/* Button Configuration */
button {
    font-weight:    normal;
    box-shadow:     none;
    margin-bottom: -8px;
    margin-top:    -8px;
    padding-right:  0;
    padding-left:   0;
}
```

> PS: Completely off topic, but I just wanted to let you know, that there seems to be a (Wayland targeted and GTK using) [Hybridbar](https://github.com/hcsubser/hybridbar),
Yeah I noticed this after seeing "Hybridbar" listed on GitHub a few weeks ago. Although that project seems dormant
