### ISSUE TITLE
No blur on hyprland

### ISSUE THREAD

**Issue by Gusser93** [vars1ty/HybridBar#26]
Hi,
I have problems getting the blur on hyprland to work. Short summary of my setup:
```
Arch
hyprland-git: commit be03a6186c22f915d3d92df71d2e74c64e816245dirty (2022-11-20)
 hybrid-bar-git: 0.3.8-1
```
decoration part of hyprland.config
```
decoration {
    rounding=10
    blur=1
    blur_size=5 
    blur_passes=2 
    blur_new_optimizations=1
    blur_ignore_opacity=1
}
```
HybridBars config.json (important part)
```json
    "hybrid": {
        "r": 10,
        "g": 10,
        "b": 10,
        "a": 0.8
    },
 ```
 
 style.css
 ```css
* {
    font-family: Roboto, "Fork Awesome";
}

label {
    color:         white;
    padding-left: 5px;
    padding-right: 5px;
}

#root {
}

#left {
    border-right: 1px solid;
    border-left: 1px solid;
}

#right {
    border-left: 1px solid;
    border-right: 1px solid;
}

#separator, #separator_ending, #separator_vol {
    background-color: white;
}

/* Button Configuration */
button {
    border-radius: 50%;
    font-weight:    normal;
    border: 1px solid;
    box-shadow: none;
    margin-bottom: 2px;
    margin-top: 2px;
    margin-right: 3px;
    margin-left: 3px;
    padding-left: 0px;
    padding-right: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    min-width: 25px;
    min-height: 25px;
    background-image: none;
    background-color: rgba(50,97,112,0.75);
}
```
While I get a nice blur on alacritty with nearly identical settings (opacity=0.8), there is no blur with HybridBar. Did I miss something? I tried different values, restarted everything, but no success. Here are two examples, the second dark bar uses the posted config, the other bars are using a different colour and opacity:
![grafik](https://user-images.githubusercontent.com/12176313/203827553-5c8089b9-5756-475c-bdef-14f66f62b79d.png)
![grafik](https://user-images.githubusercontent.com/12176313/203827733-9f59225f-704d-4893-b126-99914b8b3cb4.png)

I hope this is the right place to ask this.
